#!/usr/bin/env ruby

# converts vim chinese documentation to simple html
# author: yuweijun@live.com
# date: Fri, 18 Dec 2015 20:34:44 +0800

def mylength str
    length = str.length
    str.unpack("U*").each do |char|
      length = length + 1 if char > 255
    end

    length
end

def myexpand line
  tabstop = 8
  line = line.gsub(/([^\t]*)(\t+)/) do |match|
    $1 + (' ' * (tabstop * $2.length - (mylength($1) % tabstop)))
  end

  line
end

def mark_anchors anchors, file
  filename = file.sub(/\.cnx/, '')
  outfile = filename + '.html'
  IO.foreach(file) do |line|
    line.scan(/\*([\w.\-]+?)\*/) do |m|
      anchors[$1] = outfile + '#' + $1
    end
  end
end

def vim2html anchors, file
  filename = file.sub(/\.cnx/, '')
  outfile = filename + '.html'

  lines = []
  IO.foreach(file) do |line|
    line = myexpand(line)

    if ( /^=+\s*$/ =~ line )
      line = "\n</div>\n\n<hr class=\"doubleline\" />\n<div class=\"pre\">\n";
    elsif ( /^\s*-+\s*$/ =~ line )
      line = "\n</div>\n\n<hr class=\"singleline\" />\n<div class=\"pre\">\n";
    elsif ( /^(>)$/ =~ line )
      line = line.sub($1, "\n\n")
    elsif ( /^(<)$/ =~ line )
      line = line.sub($1, "\n\n")
    else
      # processing < and > for html tags
      line = line.sub(/<([.='\s"\/\-\w]+?)>/, '&lt;\1&gt;')
      line = line.sub(/(\s>)$/, "\n").sub(/^<(\s{3,})/, '\1')
      line = line.gsub(/>/, '&gt;').gsub(/</, '&lt;')
    end

    lines << line
  end

  document = lines.join.gsub(/\n{3,}/, "\n\n")
  document = document.gsub(/(\s+vim\w*\s+?)/, '<code class="vim">\1</code>')
  document = document.gsub(/(\s+:[\w.,!^\/\[\]\(\)$]+)/, '<code class="help">\1</code>')
  document = document.gsub(/\*([\w.\-]*?)\*/, '*<span id="\1" class="anchor">\1</span>*')

  document = document.gsub(/\|(\w\S+?)\|/) do |m|
    anchor = anchors[$1] || '#'
    "|<a href=\"#{anchor}\">#{$1}</a>|"
  end

  html = <<EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>vim中文手册</title>
    <meta name="description" content="vim7.4中文帮助文档">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="vim.css" type="text/css">
</head>
<body>
    <header class="site-header">
        <div class="wrap">
            <div class="site-title"><a href="/vim-zh/usr_toc.html">Vim中文手册</a></div>
            <div class="site-description">{"type":"documentation"}</div>
        </div>
    </header>
    <div class="page-content">
        <h2 class="vim-chapter">Vim documentation: #{filename}</h2>
        <div class="vim-document">
            <div class="pre">
#{document}
            </div>
        </div>
    </div>
    <footer class="site-footer">
        <div class="wrap">
            <div class="footer-content">
              <i>Generated by vim2html.rb on </i>
              <a href="http://www.4e00.com/vim-zh/usr_toc.html">www.4e00.com</a>
            </div>
        </div>
    </footer>
</body>
</html>
EOF

  File.open(outfile, "w") do |io|
    io.puts html
  end

end

anchors = {}
Dir.glob('*.cnx').each_with_index do |file, index|
  mark_anchors(anchors, file)
end

Dir.glob('*.cnx').each_with_index do |file, index|
  puts "#{index + 1}. processing #{file} ...\n";
  vim2html(anchors, file)
end

puts "done.\n"

