#!/usr/bin/env ruby

# converts vim chinese documentation to simple html
# author: yuweijun@live.com
# date: Fri, 18 Dec 2015 20:34:44 +0800

def mylength str
    length = str.length
    str.unpack("U*").each do |char|
      length = length + 1 if char > 255
    end

    length
end

def myexpand line
  tabstop = 8
  line = line.gsub(/([^\t]*)(\t+)/) do |match|
    $1 + (' ' * (tabstop * $2.length - (mylength($1) % tabstop)))
  end

  line
end

def vim2html file
  filename = file.sub(/\.cnx/, '')
  outfile = filename + '.html'

  lines = []
  IO.foreach(file) do |line|
    line = myexpand(line)

    if ( /^=+\s*$/ =~ line )
      line = "\n</div>\n\n<hr class=\"doubleline\" />\n<div class=\"pre\">\n";
    elsif ( /^\s*-+\s*$/ =~ line )
      line = "\n</div>\n\n<hr class=\"singleline\" />\n<div class=\"pre\">\n";
    elsif ( /^(>)$/ =~ line )
      line = line.sub($1, "\n")
    elsif ( /^(<)$/ =~ line )
      line = line.sub($1, "\n")
    else
      line = line.gsub(/<([.=\-\w]+?)>/, '&lt;\1&gt;')
      line = line.gsub(/^<|>$/, '')
      line = line.gsub(/(&lt;.*?&gt;)/, '<code class="special">\1</code>')

      line = line.gsub(/^(.*?)\~$/, '<code class="section">\1</code>')

      line = line.gsub(/(\w*CTRL-(\w+|.))/, '<code class="keystroke">\1</code>')

      line = line.gsub(/\[(range|line|count|offset|cmd|[-+]?num)\]/, '<code class="special">[\1]</code>')

      line = line.gsub(/(Note[:\s])/, '<code class="note">\1</code>')

      line = line.gsub(/^(\s*:[\w.,!^\/\[\]\(\)$]+)/, '<code class="help">\1</code>')

      line = line.gsub(/^(\s*vim\w*\s+?)/i, '<code class="vim">\1</code>')

      line = line.gsub(/\|(.*?)\.txt\|/, '|<a href="\1.html">\1.txt</a>|')

      line = line.gsub(/\|((\d+)\.\d+)\|/, '|<a href="usr_\2.html#\1">\1</a>|')

      line = line.gsub(/\|help-tags\|/, '|<a href="tags.html">help-tags</a>|')

      line = line.gsub(/\*(.*?)\*/, '*<span id="\1" class="anchor">\1</span>*')
    end

    lines << line
  end

  html = <<EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>vim中文手册</title>
    <meta name="description" content="vim7.4中文帮助文档">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="vim.css" type="text/css">
</head>
<body>
    <header class="site-header">
        <div class="wrap">
            <div class="site-title"><a href="/vim-zh/usr_toc.html">Vim中文手册</a></div>
            <div class="site-description">{"type":"programming"}</div>
        </div>
    </header>
    <div class="page-content">
        <h2 class="vim-chapter">Vim documentation: #{filename}</h2>
        <div class="vim-document">
            <div class="pre">
#{lines.join}
            </div>
        </div>
    </div>
    <footer class="site-footer">
        <div class="wrap">
            <div class="footer-content">
              <i>Generated by vim2html.rb on </i>
              <a href="http://www.4e00.com/vim-zh/usr_toc.html">4e00.com</a>
            </div>
        </div>
    </footer>
</body>
</html>
EOF

  File.open(outfile, "w") do |io|
    io.puts html
  end

end

Dir.glob('*.cnx').each_with_index do |file, index|
  puts "#{index + 1}. processing #{file} ...\n";
  vim2html(file)
end

puts "done.\n"
