#!/usr/bin/env ruby

# run command first
# ./vimtohtml.sh
# then run this command
# ./vimtohtml.rb
#
# converts vim chinese documentation to simple html
# author: yuweijun@live.com
# date: 2020-03-25 14:34:05

def mylength str
    length = str.length
    str.unpack("U*").each do |char|
      length = length + 1 if char > 255
    end
    length
end

def mark_anchors anchors, file
  filename = file.sub(/\.cnx/, '')
  outfile = filename + '.html'
  IO.foreach(file) do |line|
    line.scan(/\*([\w.\-]+?)\*/) do |m|
      anchors[$1] = outfile + '#' + $1
    end
  end
end

def vim2html anchors, file
  filename = file.sub(/\.cnx.html/, '')
  outfile = filename + '.html'
  lines = []
  File.foreach(file).with_index do |line, line_num|
    if line_num > 26 and line !~ /<\/body>|<\/html>/
      lines << line
    end
  end

  document = lines.join.gsub(/\n{3,}/, "\n\n")
  document = document.gsub(/<span class="Identifier">(\w\S+?)<\/span>/) do |m|
    anchor = anchors[$1] || '#'
    "<a href=\"#{anchor}\"><span class=\"Identifier\">#{$1}</span></a>"
  end

  html = <<EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>vim中文手册</title>
    <meta name="description" content="vim8.0 中文帮助文档">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="vim.css" type="text/css">
</head>
<body>
    <header class="site-header">
        <div class="wrap">
            <div class="site-title"><a href="/vim-zh/usr_toc.html">Vim中文手册</a></div>
            <div class="site-description">{"type":"documentation"}</div>
        </div>
    </header>
    <div class="page-content">
        <div class="wrap">
            <h2 class="vim-chapter">Vim documentation: #{filename}</h2>
            <div class="vim-document">
                <div class="pre">
#{document}
                </div>
            </div>
        </div>
    </div>
    <footer class="site-footer">
        <div class="wrap">
            <div class="footer-content">
              <i>Generated by vim2html.rb on </i>
              <a href="http://www.4e00.com/vim-zh/usr_toc.html">www.4e00.com</a>
            </div>
        </div>
    </footer>
</body>
</html>
EOF

  File.open(outfile, "w") do |io|
    io.puts html
  end
end

anchors = {}

Dir.glob('*.cnx').each_with_index do |file, index|
  mark_anchors(anchors, file)
end

Dir.glob('*.cnx.html').each_with_index do |file, index|
  puts "#{index + 1}. processing #{file} ...\n";
  vim2html(anchors, file)
end

puts "done.\n"

